name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@main

      - name: Lint
        run: bun run lint

      - name: Check unused files, dependencies, and exports
        run: bun run check:unused

      - name: Type check
        run: bun run check:types
  project-size:
    name: Analyze project build size
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@main

      - name: Analyze project build stats
        uses: kevinmarrec/workflows/project-build-stats@main
        with:
          directories: template/app,template/api
