name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@9a512216c1a1f5f20661bc1e44f9585a13744799 # main

      - name: Lint
        run: bun run lint

      - name: Check unused files, dependencies, and exports
        run: bun run check:unused

      - name: Type check
        run: bun run check:types
  project-build-size-diff:
    name: Analyze project build size differences
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@9a512216c1a1f5f20661bc1e44f9585a13744799 # main

      - name: Build project
        run: bun run build

      - name: Analyze project build size differences
        uses: kevinmarrec/workflows/filesize-diff@9a512216c1a1f5f20661bc1e44f9585a13744799 # main
        with:
          directories: app/dist,api/dist
