name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@16c265871b0b5d2affb79bf1ec090e23af66706c # main

      - name: Lint
        run: bun run lint

      - name: Check unused files, dependencies, and exports
        run: bun run check:unused

      - name: Type check
        run: bun run check:types
  project-build-size-diff:
    name: Analyze project build size differences
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@16c265871b0b5d2affb79bf1ec090e23af66706c # main

      - name: Build project
        run: bun run build

      - name: Analyze project build size differences
        uses: kevinmarrec/workflows/filesize-diff@16c265871b0b5d2affb79bf1ec090e23af66706c # main
        with:
          directories: app/dist,api/dist
