name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@v1

      - name: Lint
        run: bun run lint

      - name: Check unused files, dependencies, and exports
        run: bun run check:unused

      - name: Type check
        run: bun run check:types
  project-size:
    name: Analyze project build size
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@v1

      - name: Check api build size
        run: |
          echo "## API" >> $GITHUB_STEP_SUMMARY
          bun run .github/scripts/build-stats.md.ts api >> $GITHUB_STEP_SUMMARY

      - name: Check app build size
        run: |
          echo "## App" >> $GITHUB_STEP_SUMMARY
          bun run .github/scripts/build-stats.md.ts app >> $GITHUB_STEP_SUMMARY
