name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-and-test:
    name: Check & Test
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'chore: release')
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@197470359c0e1dee90ae8308a8cdaec4ab5a8785 # main

      - name: Lint
        run: bun run lint

      - name: Check unused files, dependencies, and exports
        run: bun run check:unused

      - name: Type check
        run: bun run check:types

      - name: Unit tests
        run: bun run test:coverage

      - name: Report coverage
        uses: davelosert/vitest-coverage-report-action@5b6122e3a819a3be7b27fc961b7faafb3bf00e4d # v2.9.0
        with:
          file-coverage-mode: all
          comment-on: none
  template-build-size-diff:
    name: Analyze template build size differences
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'chore: release')
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@197470359c0e1dee90ae8308a8cdaec4ab5a8785 # main

      - name: Build template
        run: bun -F ./template build

      - name: Analyze template build size differences
        uses: kevinmarrec/workflows/filesize-diff@197470359c0e1dee90ae8308a8cdaec4ab5a8785 # main
        with:
          directories: template/app/dist,template/api/dist
