name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-and-test:
    name: Check & Test
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'chore: release')
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@v1

      - name: Lint
        run: bun run lint

      - name: Check unused files, dependencies, and exports
        run: bun run check:unused

      - name: Type check
        run: bun run check:types

      - name: Unit tests
        run: bun run test:coverage

      - name: Report coverage
        uses: davelosert/vitest-coverage-report-action@8ab049ff5a2c6e78f78af446329379b318544a1a # v2.8.3
        with:
          file-coverage-mode: all
          comment-on: none
  template-size:
    name: Analyze template build size
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'chore: release')
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@v1

      - name: Check api build size
        run: |
          echo "## API" >> $GITHUB_STEP_SUMMARY
          bun run template/.github/scripts/build-stats.md.ts template/api >> $GITHUB_STEP_SUMMARY

      - name: Check app build size
        run: |
          echo "## App" >> $GITHUB_STEP_SUMMARY
          bun run template/.github/scripts/build-stats.md.ts template/app >> $GITHUB_STEP_SUMMARY
